import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ChevronDown, ExternalLink, Globe, RefreshCw, Trash2, Sparkles } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { Button, CopyButton, StatusBadge, cx } from './ui';
import { timeAgo } from '../lib/format';

export function DnsTable({ records }: { records: any[] }) {
  if (!records?.length) return null;
  return (
    <div className="overflow-x-auto rounded-xl border border-line">
      <table className="w-full min-w-[520px] text-left text-xs">
        <thead className="bg-surface text-muted"><tr><th className="px-3 py-2 font-medium">Type</th><th className="px-3 py-2 font-medium">Name</th><th className="px-3 py-2 font-medium">Value</th><th className="px-3 py-2 font-medium">Purpose</th><th /></tr></thead>
        <tbody>
          {records.map((r, i) => (
            <tr key={i} className="border-t border-line">
              <td className="px-3 py-2 font-mono font-semibold text-ember">{r.type}</td>
              <td className="px-3 py-2 font-mono">{r.name}</td>
              <td className="max-w-[240px] truncate px-3 py-2 font-mono" title={r.value}>{r.value}</td>
              <td className="px-3 py-2 text-muted">{r.purpose}</td>
              <td className="px-2 py-1"><CopyButton value={r.value} variant="ghost" /></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function DomainRow({ domain, onVerify, onRemove, showProject }: { domain: any; onVerify?: () => Promise<void>; onRemove?: () => void; showProject?: boolean }) {
  const [open, setOpen] = useState(domain.type === 'custom' && domain.status !== 'active');
  const [busy, setBusy] = useState(false);
  const url = `https://${domain.hostname}`;
  const verify = async () => { if (!onVerify) return; setBusy(true); try { await onVerify(); } finally { setBusy(false); } };
  return (
    <div className="glass rounded-2xl">
      <div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center">
        <div className="flex min-w-0 flex-1 items-center gap-3">
          <div className={cx('flex h-10 w-10 shrink-0 items-center justify-center rounded-xl', domain.type === 'generated' ? 'bg-ember/10 text-ember' : 'bg-info/10 text-info')}>{domain.type === 'generated' ? <Sparkles className="h-4 w-4" /> : <Globe className="h-4 w-4" />}</div>
          <div className="min-w-0">
            <a href={url} target="_blank" rel="noopener noreferrer" className="block truncate font-mono text-sm font-medium hover:text-ember">{domain.hostname}</a>
            <p className="mt-0.5 flex flex-wrap items-center gap-x-2 text-xs text-muted">
              <span>{domain.type === 'generated' ? 'Generated by Vercel' : 'Custom domain'}</span>
              {showProject && domain.projects && <Link to={`/app/projects/${domain.project_id}?tab=domains`} className="text-ember hover:underline">{domain.projects.name}</Link>}
              {domain.last_checked_at && <span>checked {timeAgo(domain.last_checked_at)}</span>}
            </p>
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <StatusBadge status={domain.status} />
          <CopyButton value={url} variant="ghost" />
          <a href={url} target="_blank" rel="noopener noreferrer" className="flex h-9 w-9 items-center justify-center rounded-xl text-muted hover:bg-surface-2 hover:text-fg" aria-label={`Open ${domain.hostname}`}><ExternalLink className="h-4 w-4" /></a>
          {onVerify && <Button variant="secondary" size="sm" onClick={verify} loading={busy} icon={<RefreshCw className="h-3.5 w-3.5" />}>Check</Button>}
          {onRemove && domain.type === 'custom' && <Button variant="ghost" size="icon" onClick={onRemove} aria-label={`Remove ${domain.hostname}`}><Trash2 className="h-4 w-4" /></Button>}
          {domain.type === 'custom' && <Button variant="ghost" size="icon" onClick={() => setOpen((o) => !o)} aria-label="Toggle DNS instructions" aria-expanded={open}><ChevronDown className={cx('h-4 w-4 transition', open && 'rotate-180')} /></Button>}
        </div>
      </div>
      <AnimatePresence initial={false}>
        {open && domain.type === 'custom' && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
            <div className="space-y-3 border-t border-line p-4 text-sm">
              {domain.last_error && <p className="rounded-xl border border-bad/25 bg-bad/10 px-3 py-2 text-bad">{domain.last_error}</p>}
              {domain.status === 'pending_attach' && <p className="text-muted">This domain will be attached to Vercel automatically after the project’s next successful deployment. Configure DNS now to save time:</p>}
              {domain.status === 'pending_verification' && <p className="text-muted">Vercel needs to verify ownership. Add the records below at your DNS provider, then click <b>Check</b>.</p>}
              {domain.status === 'misconfigured' && <p className="text-muted">The domain is attached but DNS doesn’t point to Vercel yet. Add these records (propagation can take up to 48h):</p>}
              {domain.status === 'active' && <p className="text-ok">DNS is configured correctly and the domain is serving your site.</p>}
              <DnsTable records={domain.dns_records || []} />
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
